### PR TITLE
range added in the Ecommerce

### PR DESCRIPTION
**Pull request by Dev-AkshatGupta**
Hello everyone O have added price range filter to my ecommerce .
Please review it thanks a lot.
live UI-https://deploy-preview-7--piston-parts.netlify.app/pages/products.html

### CODE REVIEW

**Comment by atul-gairola** [comment]
Hey man can you just update the live UI link, it's for your local

**Review by atul-gairola — APPROVED** [review]

**Comment by Dev-AkshatGupta** [comment]
> Hey man can you just update the live UI link, it's for your local

Thanks for reviewing that's my bad 
Correct Live-UI-https://deploy-preview-7--piston-parts.netlify.app/pages/products.html

**Review by abhisheksahani-nova — APPROVED** [review]
Looks good  to merge

**Comment by Dev-AkshatGupta** [comment]
> Looks good to merge

Thanks for reviewing it

**Pull request merged**
